gateway:
  name: Aegis API Gateway
  environment: production
  listen: # either have http or https not both if both are there https will be given preference, 
          # and if ssl is not enabled then port will fall back to http
    http: 8080
    https: 8443
  base_path: /api
  upstream_timeout_ms: 5000

ssl: # this is optional and only required if https port is selected
  enabled: true
  cert_file: /etc/certs/aegis.crt
  key_file: /etc/keys/aegis.key
  truststore_path: /etc/certs/truststore.jks
  tls_versions:
    - TLSv1.2
    - TLSv1.3

routes:
  default_backend: http://upstream-default:8080
  rules:
    - match:
        path: /auth/**
      forward_to: http://auth-service:9000
    - match:
        header:
          X-Service: profile
      forward_to: http://profile-service:8080
    - match:
        path: /static/**
      forward_to: http://static-cdn:8081

rate_limiting:
  global:
    enabled: true
    requests_per_second: 100
    burst_capacity: 200
    method: token bucket # Optional and default

throttling:
  enabled: true
  max_concurrent_requests: 500
  queue_timeout_ms: 250

caching:
  enabled: true
  method: write through # Optional and default
  rules:
    - path: /public/**
      ttl_seconds: 120
    - path: /health
      ttl_seconds: 5  

header_modification:
  add:
    X-Gateway-Version: "1.0.0"
    X-Trace-ID: "{trace_id}"
  remove:
    - X-Internal-Token

logging:
  level: INFO
  format: json
  file: /var/log/aegis/gateway.log

tracing:
  enabled: true
  format: w3c
  trace_id_header: X-Trace-ID
  exporter:
    type: hermes-notification
    endpoint: http://hermes-notification:14268/api/traces

health:
  endpoints:
    liveness: /health/live
    readiness: /health/ready

metadata:
  version: 1.0.0
  generated_at: 2025-06-24
  author: Pragyanshu Rai