gateway:
  name: Aegis API Gateway
  environment: production
  listen:
    http: 8080
    https: 8443
  base_path: /api
  upstream_timeout_ms: 5000

ssl:
  enabled: true
  cert_file: /etc/certs/aegis.crt
  key_file: /etc/keys/aegis.key
  tls_versions:
    - TLSv1.2
    - TLSv1.3

routes:
  default_backend: http://upstream-default:8080
  rules:
    - match:
        path: /auth/**
      forward_to: http://auth-service:9000
    - match:
        path: /static/**
      forward_to: http://static-cdn:8081

rate_limiting:
  global:
    enabled: true
    requests_per_second: 100
    burst_capacity: 200

throttling:
  enabled: true
  max_concurrent_requests: 500
  queue_timeout_ms: 250

caching:
  enabled: true
  rules:
    - path: /public/**
      ttl_seconds: 60

header_modification:
  add:
    X-Gateway-Version: "1.0.0"
    X-Trace-ID: "{trace_id}"
  remove:
    - X-Internal-Token

logging:
  level: INFO
  format: json

tracing:
  enabled: true
  format: w3c
  trace_id_header: X-Trace-ID
  exporter:
    type: jaeger
    endpoint: http://jaeger-collector:14268/api/traces

health:
  endpoints:
    liveness: /health/live
    readiness: /health/ready

metadata:
  version: 1.0.0
  generated_at: 2025-06-24
  author: Pragyanshu Rai
